# Generated by Django 5.0.6 on 2024-08-25 19:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_profile_picture_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Xidmət adı')),
                ('icon', models.FileField(blank=True, null=True, upload_to='', verbose_name='ikonu')),
                ('title', models.CharField(max_length=100, verbose_name='BAsliq')),
                ('description', ckeditor.fields.RichTextField(max_length=500, verbose_name='Aciqlama')),
            ],
        ),
    ]
