# Generated by Django 5.0.6 on 2024-08-27 17:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyadı')),
                ('photo', models.FileField(upload_to='')),
                ('description', ckeditor.fields.RichTextField(max_length=1000, verbose_name='Haqqında')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefon')),
                ('occupation', models.CharField(max_length=100, verbose_name='Vəzifə')),
                ('twitter', models.CharField(max_length=100, verbose_name='Twitter')),
                ('facebook', models.CharField(max_length=100, verbose_name='Facebook')),
                ('youtube', models.CharField(max_length=100, verbose_name='Youtube')),
                ('instagram', models.CharField(max_length=100, verbose_name='Instagram')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name='Açıqlama'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='İkonu'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Xidmətin adı'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlıq'),
        ),
    ]
