# Generated by Django 5.0.6 on 2024-08-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_consultant_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telefon'),
        ),
    ]
