# Generated by Django 5.0.6 on 2024-08-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_praise'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='Şəkil')),
                ('title', models.CharField(max_length=100, verbose_name='Başlıq')),
                ('category', models.CharField(max_length=100, verbose_name='Kateqoriya')),
                ('name_lastname', models.CharField(max_length=100, verbose_name='Ad və soyad')),
                ('icon', models.FileField(upload_to='', verbose_name='Şəkli')),
                ('history', models.DateTimeField(verbose_name='Tarixi')),
            ],
        ),
    ]
