# Generated by Django 5.0.6 on 2024-08-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='history',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='icon',
            field=models.FileField(upload_to='', verbose_name='Profil şəkli'),
        ),
    ]
