# Generated by Django 5.0.6 on 2024-08-29 08:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_new_history_alter_new_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slickbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='Şəkil')),
                ('title', models.CharField(max_length=100, verbose_name='Başlıq')),
                ('description', ckeditor.fields.RichTextField(max_length=500, verbose_name='Açıqlama')),
            ],
        ),
    ]
