# Generated by Django 5.0.6 on 2024-09-05 11:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_slickbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('price', models.CharField(max_length=100, verbose_name='Qiymət')),
                ('description', ckeditor.fields.RichTextField(max_length=500, verbose_name='Açıqlama')),
                ('my_list', models.CharField(default='[]', max_length=100, verbose_name='Açıqlama')),
            ],
        ),
    ]
