# Generated by Django 5.0.6 on 2024-09-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='my_list',
            field=models.CharField(default='[]', max_length=255),
        ),
    ]
