# Generated by Django 5.0.6 on 2024-09-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='', verbose_name='Şəkil')),
                ('title', models.CharField(max_length=100, verbose_name='Başlıq')),
                ('my_list', models.CharField(default='[]', max_length=255)),
            ],
        ),
    ]
