# Generated by Django 5.0.6 on 2024-09-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='title',
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='[]', max_length=100, verbose_name='Başlıq'),
        ),
    ]
