# Generated by Django 5.0.6 on 2024-09-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_contact_title_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='my_list',
        ),
        migrations.AddField(
            model_name='contact',
            name='adress',
            field=models.CharField(default='[]', max_length=200, verbose_name='Ünvan'),
        ),
        migrations.AddField(
            model_name='contact',
            name='mail',
            field=models.CharField(default='[]', max_length=100, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='contact',
            name='tel',
            field=models.CharField(default='[]', max_length=100, verbose_name='Telefon'),
        ),
    ]
