# Generated by Django 5.0.6 on 2024-09-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_contact_my_list_contact_adress_contact_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='adress',
            field=models.CharField(blank=True, default='[]', max_length=200, verbose_name='Ünvan'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mail',
            field=models.CharField(blank=True, default='[]', max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tel',
            field=models.CharField(blank=True, default='[]', max_length=100, verbose_name='Telefon'),
        ),
    ]
