# Generated by Django 5.0.6 on 2024-09-07 16:44

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_contact_adress_remove_contact_mail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Kateqoriya')),
                ('title', models.CharField(max_length=150, verbose_name='Başlıq')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Məzmun')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Şəkil')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=150, verbose_name='Müəllif')),
                ('comment_content', ckeditor.fields.RichTextField(verbose_name='Məzmun')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article', verbose_name='Məqalə')),
            ],
        ),
    ]
