# Generated by Django 5.0.6 on 2024-09-08 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_comment_article_comment_profile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
