# Generated by Django 5.0.6 on 2024-09-08 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
