# Generated by Django 5.0.6 on 2024-09-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_comment_profile_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
