# Generated by Django 5.0.6 on 2024-09-08 17:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='content',
            field=ckeditor.fields.RichTextField(default='', max_length=800, verbose_name='Məzmun'),
        ),
    ]
