# Generated by Django 5.0.6 on 2024-09-08 17:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_new_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=ckeditor.fields.RichTextField(default='', max_length=3000, verbose_name='Məzmun'),
        ),
    ]
