# Generated by Django 5.0.6 on 2024-09-09 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_comment_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='botimg',
            field=models.FileField(default='', upload_to='', verbose_name='Üst şəkil'),
        ),
        migrations.AddField(
            model_name='new',
            name='midimg',
            field=models.FileField(default='', upload_to='', verbose_name='Üst şəkil'),
        ),
        migrations.AddField(
            model_name='new',
            name='topimg',
            field=models.FileField(default='', upload_to='', verbose_name='Üst şəkil'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='new',
            field=models.ForeignKey(default='6', on_delete=django.db.models.deletion.CASCADE, to='core.new'),
        ),
    ]
