# Generated by Django 5.0.6 on 2024-09-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_new_botimg_new_midimg_new_topimg_alter_comment_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='botimg',
            field=models.FileField(default='', upload_to='', verbose_name='Alt şəkil'),
        ),
        migrations.AlterField(
            model_name='new',
            name='midimg',
            field=models.FileField(default='', upload_to='', verbose_name='Orta şəkil'),
        ),
    ]
