# Generated by Django 5.0.6 on 2024-09-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_new_botimg_alter_new_midimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='botimg',
            field=models.FileField(blank=True, default='', upload_to='', verbose_name='Alt şəkil'),
        ),
        migrations.AlterField(
            model_name='new',
            name='midimg',
            field=models.FileField(blank=True, default='', upload_to='', verbose_name='Orta şəkil'),
        ),
        migrations.AlterField(
            model_name='new',
            name='topimg',
            field=models.FileField(blank=True, default='', upload_to='', verbose_name='Üst şəkil'),
        ),
    ]
