# Generated by Django 5.0.6 on 2024-09-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_reply_comment_user_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_contact',
            name='yourconsent',
            field=models.BooleanField(default=False),
        ),
    ]
