# Generated by Django 5.0.6 on 2024-09-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_faqquestion_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='category2',
            field=models.CharField(default='', max_length=100, verbose_name='İkinci Kateqoriya'),
        ),
    ]
