# Generated by Django 5.0.6 on 2024-09-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_new_category2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='category2',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='İkinci Kateqoriya'),
        ),
    ]
