# Generated by Django 5.0.6 on 2024-09-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_newslettermessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettermessage',
            name='email',
        ),
        migrations.AddField(
            model_name='newslettermessage',
            name='mail1',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
