# Generated by Django 5.0.6 on 2024-09-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_remove_newslettermessage_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image_icon',
            field=models.FileField(default='', upload_to='', verbose_name='Şəkil ikon formasında'),
        ),
    ]
