# Generated by Django 5.0.6 on 2024-09-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_social_delete_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='link',
            field=models.CharField(blank=True, max_length=300, verbose_name='Linki'),
        ),
    ]
