# Generated by Django 5.0.6 on 2024-09-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_social_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktivdir?'),
        ),
    ]
